distribution Mail-Box-2.036.tar.gz

diff --git a/mkdist b/mkdist
--- a/mkdist
+++ b/mkdist
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-VERSION=2.035
+VERSION=2.036
 
 umask 022
 
@@ -8,6 +8,11 @@ TOP=$PWD
 BIN=$TOP/bin
 
 TMP="${TMPDIR:-/tmp}/MailBox"
+if [ -d $TMP ] || mkdir $TMP
+then :
+else echo "Cannot create $TMP: $!" >&2
+     exit 1
+fi
 
 HTML="${TMPDIR:-/tmp}/MailBox-html"
 HTMLOUT="$HTML-output"
